go101/go101

articles/packages-and-imports.html

Small fixes just to start contributing; once I get some more time I can contribute more.

packages-and-imports: typo fixes

---

articles/type-system-overview.html

Fix typo in Type System Overview page

---

articles/concurrent-common-mistakes.html

Hello TapirLiu, here are a few minor fixes. Thanks for the Go 101 book :)

Deleplace typos patch 1

---

articles/interface.html

Fix typo in interface.html

---

articles/struct.html

Fix typo in struct.html

---

articles/memory-model.html

Fix typo in memory-model.html

---

articles/101.html
articles/go-sdk.html
articles/introduction.html

Hi @TapirLiu - as I like Your content, I started reading it in my editor, and could not resist to adjust some wordings in order to allow more lucid reading. If You like it, I may be motivated to do more like this.

Small grammatical adjustments

---

README.md

@go101 You may wish to explain the subtle difference between non-cached and cached version

update `$ go101` reply text

---

articles/operators.html

change wrong operator for larger than

---

articles/function.html

typo in return isMultipleOf3(n) && isMultipleOf5(15) instead of return isMultipleOf3(n) && isMultipleOf5(n)

fix logic of isMultipleOf15

---

articles/function-declarations-and-calls.html
articles/operators.html

Thanks for compiling these notes :)

operators.html: fix minor typos, grammer.

---

articles/evaluation-orders.html
articles/memory-model.html
articles/method.html
articles/string.html
articles/type-system-overview.html

First of all thanks for a great resource!
This PR proposes fixing a few typos and potentially better wording in a couple of places.

Fix a few typos and propose potentially better wording

---

articles/container.html

fix the example's output from "Python:1991" to "Java:1995"

fix example of Append And Delete Container Elements

---

articles/channel.html
articles/function.html

fix two typos in function.html
fix three bugs in channel.html

fix two typos and three bugs

---

articles/-quizzes.html

This pull request fixes the grammatical phrasing of the sentence. 
"poorly written" sounds more appropriate than "bad written".

Correct sentence phrasing

---

articles/value-part.html

Could you please check, these ones?

Small fixes

---

articles/channel.html
articles/go-sdk.html
articles/interface.html
articles/introduction.html
articles/keywords-and-identifiers.html
articles/method.html
articles/type-embedding.html

Made a lot of changes in the following articles:
- Introduction
- Channels
- Go SDK
- Interfaces
- Keywords & Identifiers
- Method
- Type Embedding

Grammatical and rephrasing

---

articles/go-sdk.html

Just a typo-fix)
I've just started to read.

typo-fix (lcoal -> local)

---

articles/control-flows-more.html

I found this article very helpful, and am going to read through more of these articles in the future. In future, I will plan to submit edits for review only after I've actually gone through a whole page.

slight re-org for better flow and grammar

---

articles/type-system-overview.html

A lot of this is flow, and the use of "denoted".

Grammar tweaks to "type system overview"

---

articles/channel.html

Update channel.html. Grammar.

---

articles/container.html

See: https://github.com/golang/go/blob/052da5717e02659da49707873b3868fe36f2aaf0/doc/go_spec.html#L4321

articles: add edge cases for slice to array pointer conversion

---

articles/unsafe.html

See: https://github.com/golang/go/blob/052da5717e02659da49707873b3868fe36f2aaf0/src/unsafe/unsafe.go#L225

articles: add example of unsafe.Slice edge case

---

articles/type-embedding.html

Same as #201, but for promoted method value.

articles: correct promoted method value evaluation explanation

---

pages/fundamentals/type-system-overview.html

* pages/fundamentals/type-system-overview.html:
* section "Concept: Custom Generic Types and Instantiated Types"

fix typo: constarints -> constraints

---

pages/generics/444-first-look-of-custom-generics.html
pages/generics/444-first-look-of-custom-generics.md

- pages/generics/444-first-look-of-custom-generics.html
- A generic type example

fix typo: defiend -> defined

---

pages/generics/555-type-constraints-and-parameters.html
pages/generics/555-type-constraints-and-parameters.md

pages/generics/555-type-constraints-and-parameters.md
pages/generics/555-type-constraints-and-parameters.html

fix typo: missing dot and minor text

---

pages/quizzes/slice-3.html

answer has 2 numbers swapped, and doesn't even match any of the options

fix slice-3 quiz answer

---

pages/fundamentals/channel-closing.html

Hello!
This PR contains some suggestions to improve the writing of this article.
Of course, I'm open to suggestions 🙂 
By the way, congratulations on the article, it's really good 👏🏼

Writing improvements to "How to Gracefully Close Channels"

---

pages/fundamentals/concurrent-common-mistakes.html
pages/fundamentals/line-break-rules.html
pages/fundamentals/method.html
pages/fundamentals/value-copy-cost.html

Hi Tapir,
First, I want to express my deepest gratitude for writing the book "Go 101". It has been an invaluable resource as I've been learning with Go.
While reading the book, I noticed a few typos in several HTML files and thought it would be helpful to contribute towards making the content even better.
Once again, thank you for creating such a fantastic resource. I greatly appreciate it.
Best regards,
Cheng

Fix typos and improve wording
